### ISSUE TITLE
Pytorch CUDA kernel failure

### ISSUE THREAD

**Issue by riddhishb** [SCIInstitute/ShapeWorks#1161]
Upon the installation of the shapeworks with cuda environment on CLIO and BEAST servers, they have the following specs
NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2  

The pytorch and torch vison installs correctly with following
```
>>> import torch
>>> import torchvision
>>> torch.cuda.is_available()
True
>>> torch.__version__
1.7.1+cu110
``` 
But the computations are not supported
If I run a simple test such as 

`python -c "import torch;print(torch.max(torch.rand((30,30),device='cuda')))"`

it gives me the following error trace

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

This also happens with a new (non shapeworks) Conda environment using PyTorch 1.8.0 installation from the website (https://pytorch.org/).

I think there is an issue with the NVIDIA drivers and Cuda compatibility, but I cannot find a core reference to the same. This is a discussion about the same error but none of their solutions worked (https://github.com/pytorch/pytorch/issues/49161)
It might be something that we might need to take up with SCI support but I would like a better idea of such an error.

**Comment by riddhishb** [comment]
@jadie1 Would it be possible for you to take a look at this? 

Thanks

**Comment by riddhishb** [comment]
Ok Update on this! This is most definitely some sort of compatibility issue, 

I tried the same test on cibcgpu3 which has TITAN V

that has the following version

NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2

and it works well there.

I am going to relay this to support.sci to see if they have anything to say about this.

**Comment by sheryjoe** [comment]
Is this still an issue? @riddhishb @jadie1

**Comment by sheryjoe** [comment]
@jadie1 @riddhishb is this still an issue?

**Comment by riddhishb** [comment]
I think this is fine to ignore --> this is only an issue for really old GPU's it works fine for CIBC.

**Comment by sheryjoe** [comment]
Add to the online DeepSSM documentation the minimum cuda and GPU requirements. Add link to the cuda and GPU table.

**Comment by sheryjoe** [comment]
https://docs.nvidia.com/deploy/cuda-compatibility/

**Comment by akenmorris** [comment]
Not a shapeworks repo issue.
